CREATE DATABASE IF NOT EXISTS ps;

CREATE USER IF NOT EXISTS 'ps_dba'@'%' IDENTIFIED BY 'password';
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,INDEX,ALTER,REFERENCES ON `ps`.* TO 'ps_dba'@'%' WITH GRANT OPTION;

CREATE USER IF NOT EXISTS 'ps_app'@'%' IDENTIFIED BY 'password';
GRANT SELECT,INSERT ON `ps`.* TO 'ps_app'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;
